### ISSUE TITLE
I'm getting something similar

### ISSUE THREAD

**Issue by TFyre** [TFyre/bambu-farm#77]
I'm getting something similar

May 04, 2024 10:14:54 PM org.apache.camel.util.concurrent.ThreadType
INFO: The type of thread detected is PLATFORM
May 04, 2024 10:14:54 PM io.undertow.servlet
INFO: Initializing AtmosphereFramework
May 04, 2024 10:14:54 PM com.vaadin.flow.server.startup.ServletDeployer
INFO: Skipping automatic servlet registration because there is already a Vaadin servlet with the name com.vaadin.quarkus.QuarkusVaadinServlet
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereHandler com.vaadin.flow.server.communication.PushAtmosphereHandler mapped to context-path: /*
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed the following AtmosphereInterceptor mapped to AtmosphereHandler com.vaadin.flow.server.communication.PushAtmosphereHandler
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Atmosphere is using org.atmosphere.util.VoidAnnotationProcessor for processing annotation
May 04, 2024 10:14:54 PM org.atmosphere.util.ForkJoinPool
INFO: Using ForkJoinPool  java.util.concurrent.ForkJoinPool. Set the org.atmosphere.cpr.broadcaster.maxAsyncWriteThreads to -1 to fully use its power.
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol
May 04, 2024 10:14:54 PM org.atmosphere.container.JSR356AsyncSupport
INFO: JSR 356 Mapping path /VAADIN/push
May 04, 2024 10:14:54 PM io.undertow.websockets
INFO: UT026005: Adding programmatic server endpoint class org.atmosphere.container.JSR356Endpoint for path /VAADIN/push
May 04, 2024 10:14:54 PM io.undertow.websockets
INFO: UT026005: Adding programmatic server endpoint class org.atmosphere.container.JSR356Endpoint for path /VAADIN/push/
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installing Default AtmosphereInterceptors
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.CorsInterceptor : CORS Interceptor Support
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.CacheHeadersInterceptor : Default Response's Headers Interceptor
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.PaddingAtmosphereInterceptor : Browser Padding Interceptor Support
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.AndroidAtmosphereInterceptor : Android Interceptor Support
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.HeartbeatInterceptor : Heartbeat Interceptor Support
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.SSEAtmosphereInterceptor : SSE Interceptor Support
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.JSONPAtmosphereInterceptor : JSONP Interceptor Support
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.JavaScriptProtocol : Atmosphere JavaScript Protocol
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor : org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.OnDisconnectInterceptor : Browser disconnection detection
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.IdleResourceInterceptor : org.atmosphere.interceptor.IdleResourceInterceptor
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Set org.atmosphere.cpr.AtmosphereInterceptor.disableDefaults to disable them.
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor CORS Interceptor Support with priority FIRST_BEFORE_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor Default Response's Headers Interceptor with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor Browser Padding Interceptor Support with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor Android Interceptor Support with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.interceptor.HeartbeatInterceptor
INFO: HeartbeatInterceptor configured with padding value 'X', client frequency 0 seconds and server frequency 60 seconds
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor Heartbeat Interceptor Support with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor SSE Interceptor Support with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor JSONP Interceptor Support with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor Atmosphere JavaScript Protocol with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor Browser disconnection detection with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor org.atmosphere.interceptor.IdleResourceInterceptor with priority BEFORE_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Using EndpointMapper class org.atmosphere.util.DefaultEndpointMapper
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Using BroadcasterCache: org.atmosphere.cache.UUIDBroadcasterCache
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Default Broadcaster Class: org.atmosphere.cpr.DefaultBroadcaster
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Broadcaster Shared List Resources: false
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Broadcaster Polling Wait Time 100
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Shared ExecutorService supported: true
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Messaging ExecutorService Pool Size unavailable - Not instance of ThreadPoolExecutor
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Async I/O Thread Pool Size: 200
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Using BroadcasterFactory: org.atmosphere.cpr.DefaultBroadcasterFactory
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Using AtmosphereResurceFactory: org.atmosphere.cpr.DefaultAtmosphereResourceFactory
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Using WebSocketProcessor: org.atmosphere.websocket.DefaultWebSocketProcessor
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Invoke AtmosphereInterceptor on WebSocket message true
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: HttpSession supported: true
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Atmosphere is using org.atmosphere.inject.InjectableObjectFactory for dependency injection and object creation
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Atmosphere is using async support: org.atmosphere.container.JSR356AsyncSupport running under container: Undertow - 5.2.1.Final using jakarta.servlet/3.0 and jsr356/WebSocket API
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Atmosphere Framework 3.0.3.slf4jvaadin2 started.
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor  Track Message Size Interceptor using | with priority BEFORE_DEFAULT
May 04, 2024 10:14:54 PM com.vaadin.flow.server.DefaultDeploymentConfiguration
INFO: Vaadin is running in production mode.
Configuration validation failed:
        java.lang.IllegalArgumentException: SRCFG00039: The config property bambu.printers.myprinter1.model with the config value "X1C" threw an Exception whilst being converted [X1C] cannot be converted to PrinterModel
        java.lang.IllegalArgumentException: SRCFG00039: The config property bambu.printers.myprinter2.model with the config value "A1" threw an Exception whilst being converted [A1] cannot be converted to PrinterModel
java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Failed to read configuration properties
        at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
        ... 7 more
Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
        java.lang.IllegalArgumentException: SRCFG00039: The config property bambu.printers.myprinter1.model with the config value "X1C" threw an Exception whilst being converted [X1C] cannot be converted to PrinterModel
        java.lang.IllegalArgumentException: SRCFG00039: The config property bambu.printers.myprinter2.model with the config value "A1" threw an Exception whilst being converted [A1] cannot be converted to PrinterModel
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:75)
        at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:84)
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:724)
        at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
        at io.quarkus.runtime.generated.Config.createRunTimeConfig(Unknown Source)
        ... 8 more

_Originally posted by @blasirio in https://github.com/TFyre/bambu-farm/issues/62#issuecomment-2094554852_

**Comment by TFyre** [comment]
@blasirio this is not related to the original issue where the `.env` file was missing.

```
The config property bambu.printers.myprinter1.model with the config value "X1C" threw an Exception whilst being converted [X1C] cannot be converted to PrinterModel

The config property bambu.printers.myprinter2.model with the config value "A1" threw an Exception whilst being converted [A1] cannot be converted to PrinterModel
```
 
Please check the printer configuration section for values:
https://github.com/TFyre/bambu-farm?tab=readme-ov-file#printer-section

```properties
bambu.printers.myprinter1.model=unknown / a1 / a1mini / p1p / p1s / x1c
```

**Comment by TFyre** [comment]
Closing issue due to non activity
